name: build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'examples/'
      - 'art/'
      - '.run/'
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'examples/'
      - 'art/'
      - '.run/'

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: adopt
      - name: Grant gradlew execution permissions
        run: chmod +x gradlew
      - name: Start Gradle
        run: ./gradlew
      - name: Test JVM Target
        run: ./gradlew core:jvmTest
      - name: Test JS Target
        run: ./gradlew core:jsTest
