name: publish-snapshot

on:
  workflow_run:
    workflows: [ "build" ]
    branches:
      - master
    types:
      - completed

env:
  SIGNING_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
  SIGNING_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: adopt
      - name: Grant gradlew execution permissions
        run: chmod +x gradlew
      - name: Start Gradle
        run: ./gradlew
      - name: Publish core snapshot to Sonatype repository
        run: ./gradlew core:publishAllPublicationsToSonatypeRepository
      - name: Publish scene-graph snapshot to Sonatype repository
        run: ./gradlew scene-graph:publishAllPublicationsToSonatypeRepository
      - name: Publish wgpu-ffm snapshot to Sonatype repository
        run: ./gradlew wgpu-ffm:publishAllPublicationsToSonatypeRepository
      - name: Publish wgpu-natives snapshot to Sonatype repository
        run: ./gradlew wgpu-natives:publishAllPublicationsToSonatypeRepository
      - name: Publish tools snapshot to Sonatype repository
        run: ./gradlew extensions:tools:publishAllPublicationsToSonatypeRepository
      - name: Publish texture packer gradle plugins snapshot to Sonatype repository
        run: ./gradlew extensions:gradle:texturepacker:publishAllPublicationsToSonatypeRepository
